<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
//echo Mage::helper('customer')->getCustomer()->getId();
//print_r(Mage::helper('customer')->getCustomer()->getData());

?>


<div class="col-main111">
    <form action="<?php echo Mage::getUrl('testimonials/index/save') ?>" method="post">
        <?php if ($this->helper('customer')->isLoggedIn()):?>

	     <h4>Login:</h4>
	        <p id="welcomee" ><?php echo Mage::getSingleton('customer/session')->getCustomer()->getName();?></p>

	     <p>Testimonials<Br>
	        <textarea name="content" cols="40" rows="3"></textarea></p>
	         <input name="button" type="submit" value="Add item"></p>

    <?php else: ?>
            <?php echo 'Sign in to leave a review!!!!';?>
        <?php endif ?>

    </form>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $collection = $this->getCollection(); ?>
    <div class="page-title">
        <h1><?php echo $this->__('Testimonials') ?></h1>
    </div>
    <?php echo $this->getPagerHtml(); ?>
    <?php if($collection->getSize()): ?>
        <table class="data-table" id="my-custom-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><?php echo $this->__('Name') ?></th>
                <th><?php echo $this->__('Content') ?></th>
                <th><span class="nobr"><?php echo $this->__('Created') ?></span></th>
            </tr>
            </thead>
            <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($collection as $_obj): ?>
                <tr>

                    <td><span class="nobr" id="str"><?php echo $_obj->getuser_name(); ?></span></td>
                    <td id="show"><span class="nobr"><?php echo $_obj->getcontent(); ?></span></td>
                    <td><?php echo $this->formatDate($_obj->getCreated()) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-custom-table');</script>
    <?php echo $this->getPagerHtml(); ?>
    <?php else: ?>
        <p><?php echo $this->__('The collection is empty.'); ?></p>
    <?php endif ?>
